services:
  database:
    image: postgres:16.2-alpine
    container_name: database
    networks:
      - localnet-bridge
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ../database-data/postgresql/data/:/var/lib/postgresql/data/
      - ../database-data/postgresql/log/:/var/log/postgresql/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    platform: linux/amd64
    container_name: backend
    networks:
      - localnet-bridge
    ports:
      - "8000:8000"
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    command: [ '/bin/sh','-c','uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload' ]
    restart: unless-stopped
    env_file:
      - ../.env


networks:
  localnet-bridge:
    driver: bridge
